### ISSUE TITLE
Date posted is stacked if job listing doesn't contain New and Featrured

### ISSUE THREAD

**Issue by jkeohan** [jkeohan/fe-mentor-job-listings#21]
If listing doesn't contain both New/Featured this decreases the element's width and several elements stack. 

<img src="https://i.imgur.com/1qoRr8b.png"  width="300px"/>

**Comment by shubhamku044** [comment]
Hey @jkeohan, Can I fix this bug?

**Comment by jkeohan** [comment]
Hey @shubhamku044 ...by all means give it a go...

**Comment by shubhamku044** [comment]
Hey @jkeohan, I have fixed it. Please review the PR here -> https://github.com/jkeohan/fe-mentor-job-listings/pull/23
